// Code generated by "stringer -linecomment -type DependencyRelation -output dependency_relation_string.go"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DependencyRelationUnknown-1]
	_ = x[DependencyRelationDirect-2]
	_ = x[DependencyRelationTransitive-3]
}

const _DependencyRelation_name = "UnknownDirectTransitive"

var _DependencyRelation_index = [...]uint8{0, 7, 13, 23}

func (i DependencyRelation) String() string {
	i -= 1
	if i < 0 || i >= DependencyRelation(len(_DependencyRelation_index)-1) {
		return "DependencyRelation(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _DependencyRelation_name[_DependencyRelation_index[i]:_DependencyRelation_index[i+1]]
}
