// Code generated by "stringer -linecomment -type _e -output errors_string.go"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrNoGitRemoteFound-1]
	_ = x[ErrNoGitRepo-2]
}

const __e_name = "no git remote foundno git repo found"

var __e_index = [...]uint8{0, 19, 36}

func (i _e) String() string {
	i -= 1
	if i < 0 || i >= _e(len(__e_index)-1) {
		return "_e(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return __e_name[__e_index[i]:__e_index[i+1]]
}
