// Code generated by "stringer -type IDEStatus -linecomment"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IDEStatusSucceeded-100]
	_ = x[IDEStatusUnknownError-101]
	_ = x[IDEStatusAPIFail-104]
	_ = x[IDEStatusTokenInvalid-105]
	_ = x[IDEStatusAPITimeout-106]
	_ = x[IDEStatusScanDirInvalid-107]
	_ = x[IDEStatusLogFileCreationError-108]
	_ = x[IDEStatusServerFail-109]
	_ = x[IDEStatusGeneralAPIError-110]
}

const (
	_IDEStatus_name_0 = "succeededunknown error"
	_IDEStatus_name_1 = "API request failtoken invalidAPI timeoutscan dir invalidlog file creation errorserver failgeneral API error"
)

var (
	_IDEStatus_index_0 = [...]uint8{0, 9, 22}
	_IDEStatus_index_1 = [...]uint8{0, 16, 29, 40, 56, 79, 90, 107}
)

func (i IDEStatus) String() string {
	switch {
	case 100 <= i && i <= 101:
		i -= 100
		return _IDEStatus_name_0[_IDEStatus_index_0[i]:_IDEStatus_index_0[i+1]]
	case 104 <= i && i <= 110:
		i -= 104
		return _IDEStatus_name_1[_IDEStatus_index_1[i]:_IDEStatus_index_1[i+1]]
	default:
		return "IDEStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
