// Code generated by "stringer -linecomment -type textError -output error_string.go"; DO NOT EDIT.

package arkts

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrReadPackage-1]
	_ = x[ErrReadPackageLock-2]
	_ = x[ErrRootNotFound-3]
}

const _textError_name = "arkts: read oh-package.json5 failedarkts: read oh-package-lock.json5 failedarkts: root package not found, and no oh-package.json5 found"

var _textError_index = [...]uint8{0, 35, 75, 135}

func (i textError) String() string {
	i -= 1
	if i < 0 || i >= textError(len(_textError_index)-1) {
		return "textError(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _textError_name[_textError_index[i]:_textError_index[i+1]]
}
