// Code generated by "stringer -type _e -linecomment -output composer_error_string.go"; DO NOT EDIT.

package composer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrReadComposerManifest-1]
	_ = x[ErrParseComposerManifest-2]
	_ = x[ErrNoComposerFound-3]
}

const __e_name = "read composer.json failedparsing composer.json failedno composer found"

var __e_index = [...]uint8{0, 25, 53, 70}

func (i _e) String() string {
	i -= 1
	if i < 0 || i >= _e(len(__e_index)-1) {
		return "_e(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return __e_name[__e_index[i]:__e_index[i+1]]
}
