// Code generated by "stringer -type MessageLevel -linecomment -output ui_message_level_string.go"; DO NOT EDIT.

package ui

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MsgInfo-1]
	_ = x[MsgNotice-2]
	_ = x[MsgWarn-3]
	_ = x[MsgError-4]
}

const _MessageLevel_name = "InfoNoticeWarnError"

var _MessageLevel_index = [...]uint8{0, 4, 10, 14, 19}

func (i MessageLevel) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_MessageLevel_index)-1 {
		return "MessageLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MessageLevel_name[_MessageLevel_index[idx]:_MessageLevel_index[idx+1]]
}
