// Code generated by "stringer -type Status -linecomment -output ui_status_string.go"; DO NOT EDIT.

package ui

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusIdle-1]
	_ = x[StatusRunning-2]
	_ = x[StatusWaiting-3]
	_ = x[StatusSucceeded-4]
	_ = x[StatusFailed-5]
}

const _Status_name = "IDLERUNNINGWAITINGSUCCEEDEDFAILED"

var _Status_index = [...]uint8{0, 4, 11, 18, 27, 33}

func (i Status) String() string {
	i -= 1
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
