name: Murphysec feature request
description: Suggest an idea for Murphysec
title: "[Feature] "
labels: [ "kind/feature" ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you very much for your good ideas and suggestions for Murphysec

        Please help sync to the [Dev Mail List](mailto:dev@murphysec.com). You will get FASTER helpï¼[How to subscribe](mailto:support@murphysec.com)

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please make sure to search in the [issues](https://github.com/murphysecurity/murphysec/issues) first to see
        whether the same issue was reported already.
      options:
        - label: >
            I had searched in the [issues](https://github.com/murphysecurity/murphysec/issues) and found no similar
            issues.
          required: true

  - type: textarea
    attributes:
      label: Description
      description: Describe your ideas and needs.

  - type: textarea
    attributes:
      label: Use case
      placeholder: >
        What problem does this feature mainly solve, or what scenarios it is suitable for.

  - type: textarea
    attributes:
      label: Related issues
      description: Is there currently another issue associated with this?

  - type: checkboxes
    attributes:
      label: Are you willing to submit PR?
      description: >
        We very much look forward to developers or users to help develop the Murphysec together.
        If you are willing to submit a PR to implement this feature, please tick it.
      options:
        - label: Yes I am willing to submit a PR!

  - type: markdown
    attributes:
      value: "Thanks for completing our form!"
