// Code generated by "stringer -type parserError -linecomment -output gemlock_parser_error_string.go"; DO NOT EDIT.

package bundler

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrBadIndent-1]
	_ = x[ErrParseFail-2]
}

const _parserError_name = "Bad indentParseFail"

var _parserError_index = [...]uint8{0, 10, 19}

func (i parserError) String() string {
	i -= 1
	if i < 0 || i >= parserError(len(_parserError_index)-1) {
		return "parserError(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _parserError_name[_parserError_index[i]:_parserError_index[i+1]]
}
