// Code generated by "stringer -type repoConfigError -linecomment -output repo_config_error_string.go"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrRepoConfigNotFound-1]
	_ = x[ErrRepoConfigBad-2]
	_ = x[ErrRepoConfigUnsupportedVersion-3]
	_ = x[ErrRepoConfigBadAccessType-4]
}

const _repoConfigError_name = "config: no repo config foundconfig: repo config brokenconfig: repo config version unsupportedconfig: bad access type"

var _repoConfigError_index = [...]uint8{0, 28, 54, 93, 116}

func (i repoConfigError) String() string {
	i -= 1
	if i < 0 || i >= repoConfigError(len(_repoConfigError_index)-1) {
		return "repoConfigError(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _repoConfigError_name[_repoConfigError_index[i]:_repoConfigError_index[i+1]]
}
