// Code generated by "stringer -type _e -linecomment -output errors_string.go"; DO NOT EDIT.

package gradle

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrNoGradle-1]
	_ = x[ErrEvalGradleVersion-2]
}

const __e_name = "gradle: No gradle foundgradle: Eval gradle version failed"

var __e_index = [...]uint8{0, 23, 57}

func (i _e) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(__e_index)-1 {
		return "_e(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return __e_name[__e_index[idx]:__e_index[idx+1]]
}
