// Code generated by "stringer -type _e -linecomment -output error_string.go"; DO NOT EDIT.

package conan

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrConanReport-1]
	_ = x[ErrConanNotFound-2]
	_ = x[ErrGetConanVersionFail-3]
	_ = x[ErrRootNodeNotFound-4]
	_ = x[ErrReadConanJsonFail-5]
}

const __e_name = "conan report errorconan not foundget conan command version failedcan't found root node in conan info graphread conan json failed"

var __e_index = [...]uint8{0, 18, 33, 65, 106, 128}

func (i _e) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(__e_index)-1 {
		return "_e(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return __e_name[__e_index[idx]:__e_index[idx+1]]
}
