// Code generated by "stringer -type _e -linecomment -output error_string.go"; DO NOT EDIT.

package gitinfo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrNoRepoFound-1]
	_ = x[_ErrNoRemoteURLFound-2]
}

const __e_name = "gitinfo: no repogitinfo: no remote url"

var __e_index = [...]uint8{0, 16, 38}

func (i _e) String() string {
	i -= 1
	if i < 0 || i >= _e(len(__e_index)-1) {
		return "_e(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return __e_name[__e_index[i]:__e_index[i+1]]
}
