// Code generated by "stringer -type apiError -linecomment"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrTLSError-1]
	_ = x[ErrTimeout-2]
	_ = x[ErrRequest-3]
	_ = x[ErrUnprocessableResponse-4]
	_ = x[ErrTokenInvalid-5]
	_ = x[ErrBadURL-6]
	_ = x[ErrServerFail-7]
	_ = x[ErrGeneralError-8]
	_ = x[ErrValidateFail-9]
}

const _apiError_name = "api: tls errorapi: timeoutapi: request failapi: cannot process server responseapi: token invalidapi: bad URLapi: server failapi: general errorapi: validation fail"

var _apiError_index = [...]uint8{0, 14, 26, 43, 78, 96, 108, 124, 142, 162}

func (i apiError) String() string {
	i -= 1
	if i < 0 || i >= apiError(len(_apiError_index)-1) {
		return "apiError(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _apiError_name[_apiError_index[i]:_apiError_index[i+1]]
}
